# -*- coding: utf-8 -*-
"""ICP2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Zr7HJggYOsfeH-fcnY-XJ0fWfKk5U_d
"""

first_name = "Varshitha"
last_name = "Reddy"

def fullName(first_name , last_name):
  return first_name + " " + last_name

print(fullName(first_name , last_name))

str = "Good Evening"

def removeChars(string):

  res = ""
  for i in range(0,len(string),2):
    res += string[i]
  print(res)

removeChars(str)

from collections import Counter
with open('/content/drive/My Drive/input.txt', 'r') as input_file:
    lines = input_file.readlines()

output_lines = []
list_of_words = []

for line in lines:
    line = line.strip()
    with open('/content/drive/My Drive/output.txt', 'w') as output_file:
      for line in output_lines:
        output_file.write(line + '\n')
    list_of_words.extend(line.split(" "))


element_count = Counter(list_of_words)

for element, count in element_count.items():
  output_lines.append(f"{element} - Count: {count}")

with open('/content/drive/My Drive/output.txt', 'w') as output_file:
    output_file.write("Python Course" + '\n')
    output_file.write("Deep Learning Course" + '\n')
    output_file.write("Word_Count:" + '\n')
    for line in output_lines:
        output_file.write(line + '\n')

print("Output written to output.txt")

inchesList = list(map(int, input().split(",")))
cmList = []
cmList_comprehensions = []

def inchToCm(inch):
  return (inch * 2.54)

# Nested Interactive loop
for i in inchesList :
    cmList.append(inchToCm(i))

print ("Nested Interactive loop : \n", cmList)

# List Comprehension
cmList_comprehensions = [inchToCm(inch) for inch in inchesList]


print ("List Comprehension : \n", cmList_comprehensions)